lambda: http

http:
  address: ":8080"
  mode:
    debug: true
    cors: true

dynamic:
  environment:
    toolchain:
      os: linux
      arch: amd64
      compiler: node
      variant: full
    warehouse:
      local: /tmp/app-http/warehouse
      remote: s3://lambda-node-app-http
  package:
    namespace: app
    defaultVersion: v1
    preload:
      - package: api-full
        version: v1
      - package: wapi-full
        version: v1
