lambda: event

event:
  mode:
    debug: true

dynamic:
  environment:
    toolchain:
      os: linux
      arch: amd64
      compiler: node
      variant: full
    warehouse:
      local: /tmp/app-event/warehouse
      remote: s3://lambda-node-app-event
  package:
    namespace: app
    defaultVersion: v1
    preload:
      - package: appfull
        version: v1
