lambda: sqs

sqs:
  mode:
    debug: true
    run: partial
    reply: true

dynamic:
  environment:
    toolchain:
      os: linux
      arch: amd64
      compiler: node
      variant: full
    warehouse:
      local: /tmp/app-sqs/warehouse
      remote: s3://lambda-node-app-sqs
  package:
    namespace: app
    defaultVersion: v1
    preload:
      - package: app-full
        version: v1
