AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-node Event app example packaged as an AWS Lambda container image.

Resources:
  EventFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          AWS_ENDPOINT_URL: http://host.docker.internal:14569
          AWS_ENDPOINT_URL_S3: http://host.docker.internal:14569
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_S3_FORCE_PATH_STYLE: 'true'
          LAMBDA_NODE_CONFIG: /var/task/examples/apps/event/lambda/config/lambda.yaml
          LAMBDA_NODE_WAREHOUSE: /tmp/app-event/warehouse
          NODE_PATH: /var/task/examples/apps/event/lambda/node_modules
    Metadata:
      DockerContext: ../../../..
      Dockerfile: lambda-node/examples/apps/event/lambda/Dockerfile
